### ISSUE TITLE
[2] Telegram library/API on .NET.

### ISSUE THREAD

**Issue by q00Dree** [overbeered/fishie-the-telegram-news-aggregator-bot#2]
You should research already implemented Telegram bots and even more bots aggregators on .NET and realize how they subscribes and aggregates messages from multiple channels.

Our bots must can:

1. Understand commands (maybe we should implement syntax tree analyzer to execute input commands).
2. Subscribe on channel.
3. Unsubscribe from channel.
4. Check every new news on subscribed channels and aggregate only ones which are match the rules.

**Comment by DeiLux** [comment]
чет найти никак не могу как подписывать бота к чужому каналу, это вообще реально ? https://github.com/TelegramBots/Telegram.Bot

**Comment by DeiLux** [comment]
вот еще нашел ответ, боты не могут подписываться на каналы
 https://qna.habr.com/q/456621

**Comment by q00Dree** [comment]
Hm, looks like our main task is impossible. We should find another way how we can aggregate news...

**Comment by q00Dree** [comment]
Look at description of this repository https://github.com/parotikov/telegregator.
This guy seeked the same goal.

**Comment by q00Dree** [comment]
We need real telephone number and register new user - bot.
You should research in this way.

**Comment by q00Dree** [comment]
Maybe this one https://github.com/sochix/TLSharp

**Comment by q00Dree** [comment]
Or this one https://github.com/wiz0u/WTelegramClient

**Comment by q00Dree** [comment]
Looks like it's what we want

![image](https://user-images.githubusercontent.com/41568398/157237856-1457ebf5-9b13-47a9-be21-87a322733cb0.png)

**Comment by DeiLux** [comment]
это же клиент, а не бот (BotFather)

**Comment by q00Dree** [comment]
> это же клиент, а не бот (BotFather)

I don't think so, bot is not only BotFather, we can use client to create **bot as user**. It allows as the ability to subscribe on channels and so on, which are common bot can't do without concrete permissions...

**Comment by q00Dree** [comment]
Same for VK API. User API is more useful and have no constrains like admin role in chat and so on, but at the same time it's not a human, it's a bot which uses client api/code and registered as client(human).

**Comment by DeiLux** [comment]
Посмотрел эти репозитории, они по ip подключатся к телеграму, +- как мы бота подключали к чату
